[workspace]
resolver = "3"
members = ["kero", "crates/*", "examples/*", "kero-cli"]
default-members = ["kero"]

[workspace.package]
authors = ["Chevy Ray Johnston"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/feyworks/kero"