[workspace]
resolver = "3"
members = ["polywog", "crates/*", "examples/*", "polywog-cli"]
default-members = ["polywog"]

[workspace.package]
authors = ["Chevy Ray Johnston"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/feyworks/polywog"