[workspace]
resolver = "3"
members = ["crates/*", "crates/kero/examples/*", "crates/kero_spr/examples/*"]

[workspace.package]
authors = ["Chevy Ray Johnston"]
license = "MIT"
repository = "https://github.com/feyworks/feyworks"
rust-version = "1.92.0"