[package]
name = "ent_basics"
version = "0.1.0"
edition = "2024"

[dependencies]
kero = { version = "0.2.0", path = "../../../kero", features = ["lua"] }
kero_ent = { version = "0.1.0", path = "../.." }
mlua = { version = "0.11.6", features = ["lua54", "vendored"] }
