[package]
name = "text"
version = "0.1.0"
edition = "2024"
authors.workspace = true
license.workspace = true
description = "Text example."

[dependencies]
kero = { version = "0.1.0", path = "../../kero" }
env_logger = "0.11.8"
